### ISSUE TITLE
is OS X 10.8 supported ?

### ISSUE THREAD

**Issue by sunuslee** [yahoo/YMCache#22]
i saw podfile says 
   s.osx.deployment_target = "10.9"

but, can ymcache runs on 10.8 ? or which features that 10.8 can not support?

**Comment by adamkaplan** [comment]
We have done much testing against OS X versions because iOS is our primary use cases. If you'd like to test it out on 10.8, update with your results and we can discuss downgrading the minimum OS X version.

**Comment by dbgrandi** [comment]
We have *not* done much testing against OS X, is what he meant to say.

**Comment by adamkaplan** [comment]
@dbgrandi, my personal editor. Updated original comment :)

**Comment by sunuslee** [comment]
OK Thanks. I will see if i can find a 10.8 Mac :)

**Comment by adamkaplan** [comment]
@sunuslee I'm releasing 1.3.1 with OS X 10.8 as the minimum limit. Hopefully nobody experiences issues with that.

**Comment by adamkaplan** [comment]
https://github.com/yahoo/YMCache/releases/tag/1.3.1
